## githubConfigUrl is the GitHub url for where you want to configure runners
## ex: https://github.com/myorg/myrepo or https://github.com/myorg
githubConfigUrl: ""

## githubConfigSecret is the k8s secrets to use when auth with GitHub API.
## You can choose to use GitHub App or a PAT token
githubConfigSecret:
  ### GitHub PAT Configuration
  github_token: ""

## template is the PodSpec for each runner Pod
## For reference: https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#PodSpec
template:
  spec:
    containers:
      - name: runner
        image: ghcr.io/ctcampbell/github-actions-runner-container/ubuntu-actions-runner:latest
        command: ["/home/runner/run.sh"]
        volumeMounts:
          - mountPath: /home/runner/_work/_tool
            name: toolcache
    volumes:
      - name: toolcache
        hostPath:
          path: /Users/ccampbell/GitHub/Infra/k8s/actions-runner-controller/toolcache-runner-set/Data/_work/_tool
